spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

mail:
  address:
    admin: admin@gmail.com

jwt:
  # todo : 배포 시 숨기기
  secretKey: dtasdfasdfaewsrwerwerwerd324235235iojweofijwelfkjlsdnfiowejf234iojwe0f8jskldjfi
  access-token-expiration-minutes: 15
  refresh-token-expiration-minutes: 30

server:
  servlet:
    encoding:
      force-response: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG