spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl
  redis:
    host: localhost
    port: 6379
    time-to-live: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://main-database-deploy.cttgputbwbbb.ap-northeast-2.rds.amazonaws.com:13306/gulgil?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${RDS_ID}
    password: ${RDS_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true # SQL pretty print
mail:
  address:
    admin: ${ADMIN_EMAIL}
jwt:
  secretKey : ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
interpark:
  key: ${INTERPARK_API_KEY}
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
decorator:
  datasource:
    p6spy:
      enable-logging: true
env: server
logTracer: true

