spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl
  redis:
    host: localhost
    port: 6379
    time-to-live: 10000
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/maintest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: #${RDS_ID}
#    #password: #${RDS_PASSWORD}
#  jpa:
#    database: mysql   # ?? ?? ??
#    # database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # ?? ?? ??
#    hibernate:
#      ddl-auto: create
#    show-sql: true      # SQL ?? ??
#    properties:
#      hibernate:
#        format_sql: true # SQL pretty print
jwt:
  # todo : 배포 시 숨기기
  secretKey :  ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true


interpark:
  key:
